# Site settings
title: "Agilidade para Todos"
description: "Site educativo sobre metodologias ágeis Scrum e Kanban aplicadas a projetos sociais"
baseurl: "/agile"
url: "https://ceslop84.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Collections
collections:
  - ferramentas

# Language
lang: pt-BR

# Exclude from processing
exclude:
  - Gemfile.lock
  - vendor/

# Include
include:
  - _pages